name: test

on:
 pull_request:
 
jobs:
  test_build:
    name: test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: redhat-actions/buildah-build@v2
        with:
          image: test-image
          oci: true
          containerfiles: |
            ./containerfile